name: Build and publish to github repo

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peterhs73/sphinx-docs-action@v0.3.0
        with:
          python-version: "3.10"
          docs-source: docs/
          pyproject-path: .[docs]
          external-repo: Marohn-Group/mrfmsim-marohn-docs
          deploy-token: ${{ secrets.PRIVATE_TOKEN}}
